FROM openjdk:8-jre-alpine

RUN addgroup -S appgroup && adduser -S Lucas -G appgroup

RUN mkdir /home/example/
COPY ./passwordapi.jar /home/example/

EXPOSE 8080

USER Lucas

CMD ["java", "-jar", "/home/example/passwordapi.jar"]
